#### general settings
name: aim19
use_tb_logger: true
model: srgan
distortion: sr
scale: 4
gpu_ids: [4,5,6]

#### datasets
datasets:
  train:
    name: train
    mode: LQGT
    aug: noise
    noise_data: ./datasets/DF2K_aim19/Corrupted_noise/
    dataroot_GT: ./datasets/DF2K_aim19/generated/tdsr/HR
    dataroot_LQ: ./datasets/DF2K_aim19/generated/tdsr/LR
    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: val
    mode: LQGT
    dataroot_GT: ./datasets/aim19/valid-gt-clean
    dataroot_LQ: ./datasets/aim19/valid-input-noisy

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
network_D:
  which_model_D: NLayerDiscriminator
  in_nc: 3
  nf: 64
  nlayer: 3

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.999
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.999
  lr_scheme: MultiStepLR

  niter: 350000
  warmup_iter: -1  # no warm up
  lr_steps: [35000, 80000, 100000, 150000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: 0.1  # 1
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 1e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
